### ISSUE TITLE
TypeError line 20

### ISSUE THREAD

**Issue by klutchnikoff** [raguay/SelectByRegExp#4]
Hi Richard!

Line 20:
show_alert('Your Regular Expression statement is not valid.' + e)

should be replaced by something like:
show_alert('Your Regular Expression statement is not valid.' + str(e))

Thanks for your useful plugins ;-)
Nicolas.

**Comment by raguay** [comment]
Fixed with the 1.1 release. Thanks for spotting it. I guess I haven't missed typed and expression yet.
